In [1]:
import torch
import numpy as np

# 1.Create ops

In [5]:
# 1.from numpy
data = np.random.rand(3, 2)
x_data = torch.from_numpy(data)
x_data

tensor([[0.3068, 0.9767],
        [0.9202, 0.2836],
        [0.0737, 0.2639]], dtype=torch.float64)

In [21]:
x_data.numpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [7]:
#.2.from array
x_data = torch.tensor([[1, 2], [4, 5]])
x_data

tensor([[1, 2],
        [4, 5]])

In [10]:
# 3. from another tensor
x_data = torch.ones((2, 3))
y_data = torch.rand_like(x_data, dtype=torch.float)
y_data, y_data.device

(tensor([[0.2439, 0.2106, 0.9942],
         [0.5208, 0.8534, 0.7175]]),
 device(type='cpu'))

# 2. Operations

In [11]:
# 1. index and slicing
tensor = torch.ones(5, 6)
tensor[:, 1] = 0
tensor

tensor([[1., 0., 1., 1., 1., 1.],
        [1., 0., 1., 1., 1., 1.],
        [1., 0., 1., 1., 1., 1.],
        [1., 0., 1., 1., 1., 1.],
        [1., 0., 1., 1., 1., 1.]])

In [16]:
# 2.joining tensor
t1 = torch.hstack((tensor, tensor))
t1

tensor([[1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
        [1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
        [1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
        [1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
        [1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.]])

In [18]:
# 3.multiplying tensors
t1 = tensor * tensor
t1

tensor([[1., 0., 1., 1., 1., 1.],
        [1., 0., 1., 1., 1., 1.],
        [1., 0., 1., 1., 1., 1.],
        [1., 0., 1., 1., 1., 1.],
        [1., 0., 1., 1., 1., 1.]])

In [20]:
t2 = tensor @ tensor.T
t2

tensor([[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]])