In [1]:
import torch
import numpy as np

# 1. Tensor

In [3]:
tensor = torch.rand(3, 4)

In [4]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[0.0937, 0.6922, 0.3769, 0.0083],
        [0.8092, 0.7363, 0.8250, 0.1843],
        [0.0315, 0.8216, 0.0030, 0.0085]])

# 2. Auto gradient

In [10]:
import torch

x = torch.ones(5)  # input tensor
y = torch.zeros(3)  # expected output
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w)+b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

In [11]:
print('Gradient function for z =',z.grad_fn)
print('Gradient function for loss =', loss.grad_fn)

Gradient function for z = <AddBackward0 object at 0x13061adc0>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward object at 0x13061ac40>


In [14]:
loss.backward(retain_graph=True)
print(w.grad)
print(b.grad)

tensor([[0.5495, 0.6143, 0.1263],
        [0.5495, 0.6143, 0.1263],
        [0.5495, 0.6143, 0.1263],
        [0.5495, 0.6143, 0.1263],
        [0.5495, 0.6143, 0.1263]])
tensor([0.5495, 0.6143, 0.1263])
